### PR TITLE
feat: v2 input

### PR DESCRIPTION
**Pull request by jkettmann**
This PR includes v2 of the label, input, and select elements. Migrating the form-field was not necessary since all form elements will be wrapped inside a label.

### CODE REVIEW

**Comment by frabbit** [comment]
Interesting so a V2Label is actually what i described as a FormField. So it's a matter of naming actually. I would actually prefer to call it V2FormField instead of V2Label. What do you think @drinchev @JonathanStoye?

**Comment by frabbit** [comment]
Based on your implementation it might make sense to revisit the implementations of Checkbox and Toggle later.

**Comment by frabbit** [comment]
After selecting and loosing focus:

image

**Comment by jkettmann** [comment]
Yeah the same problem exists with the text input. Afaik you can't detect with css if the input has a value. So the user needs to add the `has-value` class to the label

**Comment by frabbit** [comment]
Right, I just realized that it's the same for the old one.

**Comment by frabbit** [comment]
I wonder if we should have a `--floating` modifier as we have now, that way the default implementation works out of the box without adding js.

**Comment by jkettmann** [comment]
You mean that the label is moving up when the `--floating` class is set?

**Comment by frabbit** [comment]
and by default it always sticks to the top, with the placeholder always shown.

**Comment by jkettmann** [comment]
But then we would need to set a combination of the `has-value` and `--floating`, right? I personally would leave it like it is since the `--floating` option is not documented by the design team. 

@skreutzberger what do you think?

**Comment by frabbit** [comment]
yes, only floating would be used in combination with has-value.

**Comment by frabbit** [comment]
We need some input here @JonathanStoye, @skreutzberger ;)

**Comment by skreutzberger** [comment]
I don't 100% understand the issue. Is it something which needs more clarity by the designers? If yes then please ask them directly. If not then please decide for yourself about what makes most sense. Thanks!

**Comment by JonathanStoye** [comment]
Then let's have the `--floating` modifier so it works out of the box even being a bit less fancy. @jkettmann @frabbit

**Comment by frabbit** [comment]
I still think that it's strange to call this component a Label, but it everyone else is fine, OK.

**Comment by frabbit** [comment]
@jkettmann I think it's better to make the placeholder visible in case the input is empty and `--floating` is NOT set.

**Comment by jkettmann** [comment]
> V2Label

@JonathanStoye what do you think about the naming? I'm also not sure about the naming. My thought was that it's reasonable to name the class for the label element `V2Label`. Since we won't have inputs without label according to team Rams I didn't see a need for a generic form field wrapper. But I can understand @frabbit's concern

**Comment by JonathanStoye** [comment]
Well I guess it is a `<label>` so I would say in case of doubt let's try to go with the most semantic option, no? I understand that the concerns but there is no right or wrong imho.

**Comment by jkettmann** [comment]
Ok, great. Then let's keep it like is. Can you approve @JonathanStoye @frabbit?

**Pull request merged**
